version: '3.4'
services:
    restreamer:
        image: ${RS_DOCKER_IMAGE}
        ports:
            - "${RS_HTTP_PORT}:8080"
            - "${RS_RTMP_PORT}:1935"
        networks:
            - frontend
        volumes:
            - restreamervol:/restreamer/db
            - recordingsvol:/var/restreamer/recordings
        environment:
          - RS_USERNAME=${RS_USERNAME}
          - RS_PASSWORD=${RS_PASSWORD}
          - RS_LOGLEVEL=4
          - RS_TIMEZONE=Europe/London
          - RS_SNAPSHOT_INTERVAL=1m
          - RS_AUDIO=auto
          - RS_TOKEN=${RS_TOKEN}
        deploy:
          replicas: 1
          restart_policy:
            condition: any
            delay: 5s
            window: 10s
networks:
  frontend:

volumes:
  restreamervol:
  recordingsvol:
